# This rule is not used by the project tigerbeetle-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to database.tigerbeetle.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tigerbeetle-operator
    app.kubernetes.io/managed-by: kustomize
  name: tigerbeetle-viewer-role
rules:
- apiGroups:
  - database.tigerbeetle.com
  resources:
  - tigerbeetles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - database.tigerbeetle.com
  resources:
  - tigerbeetles/status
  verbs:
  - get
