apiVersion: v2
name: tigerbeetle-operator
description: A Helm chart for deploying the TigerBeetle Kubernetes Operator
type: application
version: 0.1.1
appVersion: "0.1.1"
keywords:
  - tigerbeetle
  - operator
  - database
  - kubernetes
maintainers:
  - name: krishnacore
