apiVersion: v2
name: tigerbeetle-cluster
description: A Helm chart for deploying TigerBeetle clusters via the TigerBeetle Operator
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - tigerbeetle
  - database
  - kubernetes
maintainers:
  - name: krishnacore
